apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-compression
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-compression
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: image-compression
    spec:
      containers:
        - name: image-compression
          image: majesneo/image-compression:latest
          ports:
            - containerPort: 3001
          env:
            - name: RABBITMQ_URL
              value: amqp://rabbitmq:5672
