apiVersion: v1
kind: Service
metadata:
  name: image-resolution-conversion
spec:
  selector:
    app: image-resolution-conversion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: ClusterIP
